# Generated by Django 4.2.7 on 2025-04-22 18:19

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Categoria", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("alterado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
