# Generated by Django 4.2.7 on 2025-04-29 17:47

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
