# Generated by Django 4.2.7 on 2025-05-22 21:45

from django.db import migrations  # type: ignore


def transfer_data(apps, schema_editor):
    # Get old models
    Categoria = apps.get_model("loja", "Categoria")
    Fabricante = apps.get_model("loja", "Fabricante")
    Produto = apps.get_model("loja", "Produto")

    # Get new models
    Category = apps.get_model("loja", "Category")
    Manufacturer = apps.get_model("loja", "Manufacturer")
    Product = apps.get_model("loja", "Product")

    # Migrate categories
    cat_map = {}
    for old_cat in Categoria.objects.all():
        new_cat = Category.objects.create(
            name=old_cat.Categoria,
            created_at=old_cat.criado_em,
            altered_at=old_cat.alterado_em,
        )
        cat_map[old_cat.id] = new_cat

    # Migrate manufacturers
    manuf_map = {}
    for old_man in Fabricante.objects.all():
        new_man = Manufacturer.objects.create(
            name=old_man.Fabricante,
            created_at=old_man.criado_em,
            altered_at=old_man.alterado_em,
        )
        manuf_map[old_man.id] = new_man

    # Migrate products
    for old_prod in Produto.objects.all():
        Product.objects.create(
            name=old_prod.Produto,
            featured=old_prod.destaque,
            sale=old_prod.promocao,
            sale_msg=old_prod.msgPromocao,
            price=old_prod.preco,
            category=cat_map.get(old_prod.categoria_id),
            manufacturer=manuf_map.get(old_prod.fabricante_id),
            created_at=old_prod.criado_em,
            altered_at=old_prod.alterado_em,
            image=old_prod.image,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "loja",
            "0005_category_manufacturer_product",
        ),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
