# Generated by Django 4.2.7 on 2025-05-22 22:08

from django.db import migrations  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0006_auto_20250522_1845"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="fabricante",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Fabricante",
        ),
        migrations.DeleteModel(
            name="Produto",
        ),
    ]
