# Generated by Django 4.2.7 on 2025-05-12 16:48

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="msgPromocao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
